hosts: [@SERVER.HOST@]
port: @SERVER.PORT@
username: admin
password: admin
#connectionPool: {
#  enableSsl: true,
#  sslEnabledProtocols: [TLSv1.2] }
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
